### ISSUE TITLE
Saxa não sabe promovar (ODEIO)

### ISSUE THREAD

**Issue by WalterHenri** [WalterHenri/FreshFish#16]
ajeite ai na moral

**Comment by MarcosVinicius-Mota** [comment]
Odeio você e a saxa

**Comment by MustacherDev** [comment]
KDDKDKDKDKSKSKSXKAKCKXCNXNVSVNCJZXZKXMZKNC

**Comment by MarcosVinicius-Mota** [comment]
Vsf, tem um !waitPromotion.
Aliás, promove sempre rinha fds?

Em sex., 6 de out. de 2023 07:15, Mustacher ***@***.***>
escreveu:

**Comment by MustacherDev** [comment]
PRO MOVEU
