### ISSUE TITLE
fazer o banco de dados da abertura

### ISSUE THREAD

**Issue by WalterHenri** [WalterHenri/FreshFish#7]
criar uma pasta com o nome arquivo aberturas.
a abertura deve seguir o formato FEN, a nota da abertura deve ser a primeira nota pra branco, e a segunda nota pra preto.
Exemplo

0.6
0.4

d4 d5 c4 dxc5

**Comment by WalterHenri** [comment]
no minimo 30.

**Comment by M4RCOSVS0** [comment]
já fiz isso!!!!!!!
